#!/bin/sh
##SBATCH -q urgent
##SBATCH -q debug
#SBATCH --cluster=c5
#SBATCH -t 02:00:00
#SBATCH -A nggps_psd
#SBATCH -N 80    
#SBATCH -J C192_hybcov_6hourly
#SBATCH -e C192_hybcov_6hourly.err
#SBATCH -o C192_hybcov_6hourly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='gaea'

# for control forecast
if [ $NODES -eq 10 ]; then
  # 20 nodes, 1 threads
  #export control_threads=2 # control forecast threads
  #export control_proc=444   # total number of processors for control forecast
  export control_threads=1
  export control_proc=312
  export write_groups_ctl=4 # write groups for control forecast.
  export layout_ctl="6,8" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 20 ] || [ $NODES -eq 21 ]; then
  # 20 nodes, 3 threads
  #export control_threads=2 # control forecast threads
  #export control_proc=444   # total number of processors for control forecast
  export control_threads=3
  export control_proc=666
  export control_proc_noquilt=648
  export write_groups_ctl=1 # write groups for control forecast.
  export layout_ctl="6,6" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 40 ] || [ $NODES -eq 41 ]; then
  # 40 nodes, 6 threads
  export control_threads=6 
  export control_proc=1332 
  export control_proc_noquilt=1296
  export write_groups_ctl=1
  export layout_ctl="6, 6"
elif [ $NODES -eq 80 ]; then
  # 80 nodes, 6 threads
  export control_threads=6
  export control_proc=2664 
  export write_groups_ctl=1
  export layout_ctl="12, 12" 
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

# for ensemble forecast and GSI
export fg_proc=$corespernode 
#export fg_proc=`expr 2 \* $corespernode`
export fg_threads=1
export write_groups=1
if [ $corespernode -eq 128 ]; then
export enkf_threads=32
export gsi_control_threads=32
export write_groups=1
export write_tasks=8 
export layout="4, 5" 
elif [ $corespernode -eq 36 ]; then
export enkf_threads=36
export gsi_control_threads=9
export write_groups=1
#export write_tasks=12 
#export layout="2, 2" 
export write_tasks=18 
export layout="3, 3" 
elif [ $corespernode -eq 32 ]; then
export enkf_threads=8
export gsi_control_threads=4
export write_groups=1
export write_tasks=8 
export layout="2, 2" 
elif [ $corespernode -eq 24 ]; then
export layout="3, 1" 
else
echo "layout for ensemble forecast not specified for corespernode=$corespernode"
exit 1
fi
