#!/bin/sh
#SBATCH -q urgent
##SBATCH -q debug
#SBATCH --clusters c4
#SBATCH -t 01:00:00
##SBATCH -t 00:30:00
#SBATCH -A nggps_psd
##SBATCH -A cpo_ngrr_e
#SBATCH -N 40    
#SBATCH -J C192_hybcov_hourly
#SBATCH -e C192_hybcov_hourly.err
#SBATCH -o C192_hybcov_hourly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='gaea'

# for ensemble forecast and GSI
#export fg_proc=$corespernode 
export fg_proc=`expr 2 \* $corespernode`
export fg_threads=1
export write_groups=1
if [ $corespernode -eq 36 ]; then
export enkf_threads=18
export gsi_control_threads=9
export write_groups=1
#export write_tasks=12 
#export layout="2, 2" 
export write_tasks=18 
export layout="3, 3" 
elif [ $corespernode -eq 32 ]; then
export enkf_threads=8
export gsi_control_threads=4
export write_groups=1
export write_tasks=8 
export layout="2, 2" 
elif [ $corespernode -eq 24 ]; then
export layout="3, 1" 
else
echo "layout for ensemble forecast not specified for corespernode=$corespernode"
exit 1
fi
