#!/bin/sh
#SBATCH -q urgent
#SBATCH --clusters c4
#SBATCH -t 16:00:00
#SBATCH -A nggps_psd
##SBATCH -A cpo_ngrr_e
#SBATCH -N 20    
#SBATCH -J C192C384_hybgain
#SBATCH -e C192C384_hybgain.err
#SBATCH -o C192C384_hybgain.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='gaea'

# for control forecast
if [ $NODES -eq 10 ]; then
  # 20 nodes, 1 threads
  #export control_threads=2 # control forecast threads
  #export control_proc=444   # total number of processors for control forecast
  export control_threads=1
  export control_proc=312
  export write_groups_ctl=4 # write groups for control forecast.
  export layout_ctl="6,8" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 20 ]; then
  # 20 nodes, 3 threads
  #export control_threads=2 # control forecast threads
  #export control_proc=444   # total number of processors for control forecast
  export control_threads=3
  export control_proc=666
  export write_groups_ctl=1 # write groups for control forecast.
  export layout_ctl="6,6" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 40 ] || [ $NODES -eq 41 ]; then
  # 40 nodes, 6 threads
  export control_threads=6 
  export control_proc=1332 
  export control_proc_noquilt=1296
  export write_groups_ctl=1
  export layout_ctl="6, 6"
elif [ $NODES -eq 80 ]; then
  # 80 nodes, 6 threads
  export control_threads=6
  export control_proc=2664 
  export write_groups_ctl=1
  export layout_ctl="12, 12" 
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

# for ensemble forecast and GSI
export enkf_threads=6
export gsi_control_threads=3
export fg_proc=$corespernode 
export fg_threads=1 
export write_groups=2
export write_tasks=6 
export layout="2, 2" 
