#!/bin/sh
#SBATCH -q debug
#SBATCH -t 00:30:00
#SBATCH -A gsienkf   
##SBATCH -A isp-1
#SBATCH -N 40    
#SBATCH -J C192_hybcov_hourly
#SBATCH -e C192_hybcov_hourly.err
#SBATCH -o C192_hybcov_hourly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='hera'
export enkf_threads=10
export gsi_control_threads=4
