#!/bin/sh
#SBATCH -q urgent
#SBATCH -t 06:00:00
#SBATCH -A gsienkf
#SBATCH -N 80  
#SBATCH --ntasks-per-node=40
#SBATCH -p orion
#SBATCH -J C384_hybcov_hourly
#SBATCH -e C384_hybcov_hourly.err
#SBATCH -o C384_hybcov_hourly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='orion'

# for control forecast
if [ $NODES -eq 20 ]; then
  # 20 nodes, 2 threads
  export control_threads=2
  export control_proc=800
  export write_groups_ctl=4 # write groups for control forecast.
  export write_tasks_ctl=4
  export layout_ctl="8,8" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 40 ]; then
  # 40 nodes, 4 threads
  export control_threads=4 
  export control_proc=1600 
  export write_groups_ctl=4
  export write_tasks_ctl=4
  export layout_ctl="8, 8"
  # 32 nodes, 4 threads
  #export control_threads=4 
  #export control_proc=1280 
  #export write_groups_ctl=4
  #export write_tasks_ctl=8
  #export layout_ctl="8, 6"
elif [ $NODES -eq 80 ]; then
  # 80 nodes, 4 threads
  export control_threads=8 
  export control_proc=3200 
  export write_groups_ctl=4
  export write_tasks_ctl=4
  export layout_ctl="8, 8"
elif [ $NODES -eq 160 ]; then
  # 160 nodes, 8 threads
  export control_threads=8 
  export control_proc=6400 
  export write_groups_ctl=4
  export write_tasks_ctl=8
  export layout_ctl="8, 16"
elif [ $NODES -eq 320 ]; then
  # 160 nodes, 8 threads
  export control_threads=8 
  export control_proc=12800 
  export write_groups_ctl=4
  export write_tasks_ctl=16
  export layout_ctl="16, 16"
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

# for ensemble forecast and GSI
# for C192
#export fg_proc=$corespernode
#export fg_threads=1 
#export enkf_threads=10
#export gsi_control_threads=4
#export write_groups=4
#export write_tasks=1 
#export layout="3, 2"

# for C384
export fg_proc=`expr 2 \* $corespernode`
export fg_threads=1 
export enkf_threads=40
export gsi_control_threads=20
export write_groups=2
export write_tasks=4 
export layout="3, 4"
